version: 2

jobs:
  lint:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y python3-pip
      - run: pip3 install -U black flake8
      - run: LC_ALL=C.UTF-8 black --check .
      - run: flake8 setup.py pyfoobar/ test/*.py
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip gnuplot
      - run: pip3 install -U pytest pytest-cov
      - checkout
      - run: pip3 install .
      - run: pip3 install -r test_requirements.txt
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov asciiplotlib
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash) -R ~/work

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
